version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nube/gino_servicios/prisma-back
    overwrite: true
hooks:
  ApplicationStart:
    - location: scripts/flask.sh
      timeout: 3600
